### ISSUE TITLE
binary_sensor.everyone_home flags to on during HA restart even if not everyone is home.

### ISSUE THREAD

**Issue by skynet01** [Odianosen25/Monitor-App#53]
Noticed this on the current none dev branch, when HA restarts **binary_sensor.everyone_home** is marked on even though some people are not home.

I have this in my automation (from before your plugin.. but this shouldn't affect it) 

```
 - id: reboot_presence_monitoring  
  alias: Restart Presence Scan on boot
  initial_state: 'on'
  trigger:
    platform: homeassistant
    event: start
  mode: single
    - service: mqtt.publish
      data_template:
          topic: 'monitor/scan/restart'
          payload: >-
            {
              "message": ""
            }  

```
