### ISSUE TITLE
Idea: Interval scan on open "gateways".

### ISSUE THREAD

**Issue by pointlevel** [Odianosen25/Monitor-App#56]
This app is really awesome. Finally i can start using Monitor again. 

I have an idea that maybe should be a good thing. 

During summer, at least i and probably many with me, is keeping doors open during the day. And if i have this door set as a gateway, the scan will not execute in a very long time. So if we could have "smarter" gateways would be lovely in this kind of scenario. Im thinking like: 

```
home_gateway_sensors:
  frontdoor: (Full example setup)
    entity_id: binary_sensor.frontdoor    (ID of the sensor. Required)
    state_open: 'on'    (What state of this specific sensor is equal to open. Optional)
    state_closed: 'off'    (What state of this specific sensor is equal to closed. Optional)
    scan_if_kept_open: true    (Start interval-scan if open more than some time, 5mins? Optional)
    scan_time: 2    (Time between scans in minutes. Optional)
  backdoor: (Minimum setup, functionality as of today)
    entity_id: binary_sensor.backdoor
```
Of course this could be made with automation in HomeAssistant, but would preferable live inside this app.
See this only as a suggestion, i love the app anyway ;)
